import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "../components/layouts/header";
import BrandingTheme from "../components/layouts/theme-provider";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import { Provider } from "react-redux";
import store from "../redux/store";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

console.log(store, "-- store ");
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* <Provider store={store}> */}
        <BrandingTheme>{children}</BrandingTheme>
        {/* </Provider> */}
      </body>
    </html>
  );
}
